
env:
    - MY_ENV=foo
    - MY_ENV=bar

install:
    - echo "Travis install step here."
    - ./travis-script.sh

script:
    - echo "Travis script step here."
    - ./travis-script.sh

before_deploy:
    - hostname > deploy-preparation.txt

deploy:
    - provider: script
    - script: ./travis-deploy.sh deploy-preparation.txt
