
language: generic

cache:
    directories:
        - $HOME/.stack
    timeout: 1200

install:
    - bash --login travis-install.sh
    - rvm reload

script:
    - hlint

jobs:
    include:

      # - stage: test
      # os: osx
      # osx_image: xcode6.4
      # 
      # - stage: test
      # os: osx
      # osx_image: xcode8
      # 
      # - stage: test
      # os: osx
      # osx_image: xcode9.2
      # 
      # - stage: test
      # os: osx
      # osx_image: xcode10

        - stage: test
          os: osx
          osx_image: xcode8

        - stage: "After the cache is warm"
          os: osx
          osx_image: xcode8
