
language: generic

install:
    - source travis-install.sh

script:
    - homebrew_automation.rb help

jobs:
    include:

      # - stage: test
      # os: osx
      # osx_image: xcode6.4
      # 
      # - stage: test
      # os: osx
      # osx_image: xcode8
      # 
      # - stage: test
      # os: osx
      # osx_image: xcode9.2
      # 
      # - stage: test
      # os: osx
      # osx_image: xcode10

        - stage: test
          os: osx
          osx_image: xcode8

        - stage: "After the cache is warm"
          os: osx
          osx_image: xcode8
          install:
              - cat .ruby-version
              - rvm use "$(cat .ruby-version)" --install
              - which -a ruby
              - which -a gem
              - ruby --version
              - gem --version
              - gem install homebrew_automation -v 0.0.8
