
language: minimal

env:
    - MY_ENV=foo
    - MY_ENV=bar

install:
    - echo "Travis install step here."
    - ./travis-script.sh

script:
    - echo "Travis script step here."
    - ./travis-script.sh

before_deploy:
    - pwd
    - hostname | tee deploy-preparation.txt

deploy:
    provider: script
    script: ./travis-deploy.sh deploy-preparation.txt
    skip_cleanup: true
