
language: generic

install:
    - ./travis-install.sh

script:
    - homebrew_automation.rb help

jobs:
    include:

        - stage: test
          os: osx
          osx_image: xcode6.4

        - stage: test
          os: osx
          osx_image: xcode8

        - stage: test
          os: osx
          osx_image: xcode9.2

        - stage: test
          os: osx
          osx_image: xcode10
