
language: ruby

#cache:
#    directories:
#        - $HOME/.rvm
#    timeout: 1200

install:
    - which -a ruby
    - which -a gem

script:
    - ruby --version
    - gem --version

jobs:
    include:

      # - stage: test
      # os: osx
      # osx_image: xcode6.4
      # 
      # - stage: test
      # os: osx
      # osx_image: xcode8
      # 
      # - stage: test
      # os: osx
      # osx_image: xcode9.2
      # 
      # - stage: test
      # os: osx
      # osx_image: xcode10

        - stage: test
          os: osx
          osx_image: xcode6.4

        - stage: test
          os: osx
          osx_image: xcode8

        - stage: test
          os: osx
          osx_image: xcode9.2

        - stage: test
          os: osx
          osx_image: xcode10
