
language: minimal

# env:
#     - MY_ENV=foo
#     - MY_ENV=bar

matrix:
    include:
        - os: linux
          sudo: false
          env: MY_ENV=linux_env
        - os: osx
          osx_image: xcode10
          env: MY_ENV=osx_env

install:
    - echo "Travis install step here."
    - ./travis-script.sh

script:
    - echo "Travis script step here."
    - ./travis-script.sh

before_deploy:
    - echo "before_deploy here"
    - hostname
    - pwd

deploy:
  provider: script
  script: hostname && pwd && echo "deploy step here"
  skip_cleanup: true
