
language: minimal

env:
    - MY_ENV=foo
    - MY_ENV=bar

jobs:
    include:
        - stage: "test"
          install:
            - echo "Travis install step here."
            - ./travis-script.sh
          script:
            - echo "Travis script step here."
            - ./travis-script.sh
        - stage: "Now deploy!"
          script: hostname && pwd
          before_deploy:
              - pwd
              - hostname | tee deploy-preparation.txt
          deploy:
              provider: script
              script: ./travis-deploy.sh deploy-preparation.txt
              skip_cleanup: true
