
language: minimal

jobs:
    include:
        - stage: test
          os: linux
          sudo: false
          env: MY_ENV=linux_env

          install:
              - echo "Travis install step here."
              - ./travis-script.sh
          script:
              - echo "Travis script step here."
              - ./travis-script.sh
          before_deploy:
              - hostname
              - pwd
          deploy:
            provider: script
            script: hostname && pwd
            skip_cleanup: true

        - stage: test
          os: osx
          osx_image: xcode10
          env: MY_ENV=osx_env

          install:
              - echo "Travis install step here."
              - ./travis-script.sh
          script:
              - echo "Travis script step here."
              - ./travis-script.sh
          before_deploy:
              - hostname
              - pwd
          deploy:
            provider: script
            script: hostname && pwd
            skip_cleanup: true

        - stage: "Now deploy!"
          os: linux
          sudo: false
          env: MY_ENV=deploying
          install: echo "nothing to install"
          script: hostname && pwd
          before_deploy:
              - pwd
              - hostname | tee deploy-preparation.txt
          deploy:
              provider: script
              script: ./travis-deploy.sh deploy-preparation.txt
              skip_cleanup: true
