
language: generic

install:
    - uname -a
    - sw_vers -productVersion || echo 'Not sure'

    - brew --version
    - brew docter || true
    - brew upgrade || true
    - brew --version

    - rvm version
    - rvm get stable
    - rvm version

    - cat .ruby-version
    - rvm use "$(cat .ruby-version)" --install
    - which -a ruby
    - which -a gem
    - ruby --version
    - gem --version

    - gem install homebrew_automation -v 0.0.8

script:
    - echo "Travis script step here."
    - homebrew_automation.rb help

jobs:
    include:

        - stage: test
          os: osx
          osx_image: xcode6.4

        - stage: test
          os: osx
          osx_image: xcode8

        - stage: test
          os: osx
          osx_image: xcode9.2

        - stage: test
          os: osx
          osx_image: xcode10
