
language: ruby

rvm:
    - 2.5.1

install:
    - echo "Travis install step here."
    - ./travis-install.sh

script:
    - echo "Travis script step here."
    - ./travis-script.sh

before_deploy:
    - echo "Travis before_deploy step (in the test stage) here."
    - hostname
    - pwd

deploy:
    provider: script
    script: hostname && pwd && echo "OS-specific deploy prep here"
    skip_cleanup: true

jobs:
    include:

        - stage: test
          os: osx
          osx_image: xcode8

        - stage: test
          os: osx
          osx_image: xcode9.2

        - stage: test
          os: osx
          osx_image: xcode10

        - stage: "Now deploy!"
          os: linux
          sudo: false
          install: echo "nothing to install"
          script: hostname && pwd
          before_deploy:
              - echo "Travis before_deploy step (in the deploy stage) here."
              - pwd
              - hostname | tee deploy-preparation.txt
          deploy:
              provider: script
              script: ./travis-deploy.sh deploy-preparation.txt
              skip_cleanup: true
