
language: ruby

cache:
    directories:
        - $HOME/.rvm
    timeout: 1200

install:
    - gem install homebrew_automation -v 0.0.8

script:
    - homebrew_automation.rb --help

jobs:
    include:

      # - stage: test
      # os: osx
      # osx_image: xcode6.4
      # 
      # - stage: test
      # os: osx
      # osx_image: xcode8
      # 
      # - stage: test
      # os: osx
      # osx_image: xcode9.2
      # 
      # - stage: test
      # os: osx
      # osx_image: xcode10

        - stage: test
          os: osx
          osx_image: xcode6.4

        - stage: test
          os: osx
          osx_image: xcode8

        - stage: test
          os: osx
          osx_image: xcode9.2

        - stage: test
          os: osx
          osx_image: xcode10
