
language: minimal

install:
    - echo "Travis install step here."
    - ./travis-script.sh
script:
    - echo "Travis script step here."
    - ./travis-script.sh
before_deploy:
    - echo "Travis before_deploy step (in the test stage) here."
    - hostname
    - pwd
deploy:
    provider: script
    script: hostname && pwd && echo "OS-specific deploy prep here"
    skip_cleanup: true

jobs:
    include:
        - stage: test
          os: linux
          sudo: false
          env: MY_ENV=linux_env

        - stage: test
          os: osx
          osx_image: xcode8
          env: MY_ENV=osx_env
          install:
              - echo "Travis install step, specifically for OS X (xcode8), here."
              - brew install --verbose haskell-stack

        - stage: "Now deploy!"
          os: linux
          sudo: false
          env: MY_ENV=deploying
          install: echo "nothing to install"
          script: hostname && pwd
          before_deploy:
              - echo "Travis before_deploy step (in the deploy stage) here."
              - pwd
              - hostname | tee deploy-preparation.txt
          deploy:
              provider: script
              script: ./travis-deploy.sh deploy-preparation.txt
              skip_cleanup: true
